package br.com.ifes.videolocadora.service.domain.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CategoriaEnum {
	ACAO,
	ACAO_AVENTURA,
	AVENTURA,
	CINEMA_ARTE,
	CHANCHADA,
	COMEDIA,
	COMEDIA_ACAO,
	COMEDIA_TERROR,
	COMEDIA_DRAMATICA,
	COMEDIA_ROMANTICA,
	DANCA,
	DOCUMENTARIO,
	DOCUFICCAO,
	DRAMA,
	ESPIONAGEM,
	FANTASIA,
	FANTASIA_CIENTIFICA,
	FICCAO_CIENTIFICA,
	GUERRA,
	HISTORICO,
	MISTERIO,
	MUSICAL,
	POLICIAL,
	PORNOGRAFIA,
	ROMANCE,
	SUSPENSE,
	TERROR,
}
